/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DealsImport } from './routes/deals'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
	id: '/login',
	path: '/login',
	getParentRoute: () => rootRoute,
} as any)

const DealsRoute = DealsImport.update({
	id: '/deals',
	path: '/deals',
	getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
	id: '/',
	path: '/',
	getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
	interface FileRoutesByPath {
		'/': {
			id: '/'
			path: '/'
			fullPath: '/'
			preLoaderRoute: typeof IndexImport
			parentRoute: typeof rootRoute
		}
		'/deals': {
			id: '/deals'
			path: '/deals'
			fullPath: '/deals'
			preLoaderRoute: typeof DealsImport
			parentRoute: typeof rootRoute
		}
		'/login': {
			id: '/login'
			path: '/login'
			fullPath: '/login'
			preLoaderRoute: typeof LoginImport
			parentRoute: typeof rootRoute
		}
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	'/': typeof IndexRoute
	'/deals': typeof DealsRoute
	'/login': typeof LoginRoute
}

export interface FileRoutesByTo {
	'/': typeof IndexRoute
	'/deals': typeof DealsRoute
	'/login': typeof LoginRoute
}

export interface FileRoutesById {
	__root__: typeof rootRoute
	'/': typeof IndexRoute
	'/deals': typeof DealsRoute
	'/login': typeof LoginRoute
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath
	fullPaths: '/' | '/deals' | '/login'
	fileRoutesByTo: FileRoutesByTo
	to: '/' | '/deals' | '/login'
	id: '__root__' | '/' | '/deals' | '/login'
	fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute
	DealsRoute: typeof DealsRoute
	LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	DealsRoute: DealsRoute,
	LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/deals",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/deals": {
      "filePath": "deals.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
